apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: expresso-reviews-2
spec:
  minAvailable: 1
  selector:
    matchLabels:  
       app2: expresso-shop-reviews-v2
       version2: v2
       {{- include "expresso-shop-reviews.selectorLabels" . | nindent 4 }}