{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: serviceaccv2
  #name: {{ include "expresso-shop-reviews.serviceAccountName" . }}
  labels:
    app2: expresso-shop-reviews-v2
    {{- include "expresso-shop-reviews.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
