apiVersion: v1
kind: Service
metadata:
  name: expresso-shop-product-catalog-svc
  #name: {{ include "expresso-shop-product.fullname" . }}
  labels: 
    #name: expresso-shop-product-catalog-svc
     {{- include "expresso-shop-product.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: expresso-shop-product
    # {{- include "expresso-shop-product.selectorLabels" . | nindent 4 }}
