apiVersion: v1
kind: Secret
metadata:
  name: product-to-postgres-secret
type: Opaque
data:
  username: "cG9zdGdyZXM="
 
  password: "cG9zdGdyZXM="
  database: "cG9zdGdyZXM="


# username: "postgres"
# password: "postgres"
# database: "postgres